services:

  app:
    container_name: application
    build: 
      context: ./application
    ports:
     - "8000:8000"
    environment:
        DB_HOST: database
        DB_USER: postgres
        DB_PASS: password
        DB_NAME: postgres
    depends_on:
        - database

  initialiser_db:
    container_name: initialiser_db
    build: ./initialiser_db
    ports:
     - "2424:2424"
    environment:
        DB_HOST: database
        DB_USER: postgres
        DB_PASS: password
        DB_NAME: postgres
    depends_on:
          database:
            condition: service_healthy

  database:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
        - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db_data: