services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - database
  app:
    container_name: application
    build: 
      context: ./application/
    ports:
     - "8000:8000"
    environment:
        DB_HOST: database
        DB_USER: ${POSTGRES_USER}
        DB_PASS: ${POSTGRES_PASSWORD}
        DB_NAME: ${POSTGRES_DB}
    depends_on:
        - database

  database:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - db_data:/var/lib/postgresql/data
        - ./db/init:/docker-entrypoint-initdb.d  # scripts SQL de remplissage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db_data: