services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      database:
        condition: service_healthy
  app:
    container_name: application
    build: ./application/
    ports:
     - "8000:8000"
    environment:
        DB_HOST: database
        DB_USER: ${POSTGRES_USER}
        DB_PASS: ${POSTGRES_PASSWORD}
        DB_NAME: ${POSTGRES_DB}
    depends_on:
          database:
            condition: service_healthy

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
        - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
