services:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - database
  app:
    container_name: application
    build: 
      context: ./application
    ports:
     - "8000:8000"
    environment:
        DB_HOST: database
        DB_USER: test
        DB_PASS: test
        DB_NAME: test_db
    depends_on:
        - database

  initialiser_db:
    container_name: initialiser_db
    build: ./initialiser_db/
    ports:
     - "2424:2424"
    environment:
        DB_HOST: database
        DB_USER: test
        DB_PASS: test
        DB_NAME: test_db
    depends_on:
          database:
            condition: service_healthy

  database:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    volumes:
        - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db_data: