services:
  app:
    container_name: application
    build: ./application/
    ports:
     - "8000:8000"
    environment:
        DB_HOST: database
        DB_USER: ${POSTGRES_USER}
        DB_PASS: ${POSTGRES_PASSWORD}
        DB_NAME: ${POSTGRES_DB}
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    #build: ./database/
    #restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - '3306:3306'