version: "3.9"


services:
  test_database:
    image: postgres:15
    container_name: test_database
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: 
      context: ./application/
    container_name: app_test
    environment:
      DB_HOST: test_database
      DB_USER: test_user
      DB_PASS: test_password
      DB_NAME: test_db
    depends_on:
      test_database:
        condition: service_healthy
    ports:
      - "8001:8000"  

volumes:
  test_db_data:

