name: Python Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" 
      - run: pip install ruff
      - run: ruff check .


  test:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies locally
        run: |
          python -m pip install --upgrade pip
          pip install -r application/requirements.txt

      - name: Run tests with pytest
        run: pytest tests/
      
      - name: Upload pytest test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports-${{ matrix.python-version }}
          path: pytest-report-${{ matrix.python-version }}.xml
        

  build_and_push:
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Debug paths
        run: |
          pwd
          ls -la
          ls -la application || true

      - name: Run Docker Compose
        run: docker compose -f docker-compose_test.yml up -d
      
      - name: Compute lowercase image tag
        run: |
          REPO_LC="${GITHUB_REPOSITORY,,}"             # -> owner/repo en minuscules
          echo "IMAGE=ghcr.io/${REPO_LC}:latest" >> $GITHUB_ENV


      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: application         
          file: application/Dockerfile   
          tags: ${{ env.IMAGE }}
          push: true

  stop:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Stop services
        if: always()
        run: docker compose -f docker-compose_test.yml down -v

