name: Python Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and start services
        run: docker-compose -f docker-compose.test.yml up -d --build

    #name: Run tests inside container
      #run: docker-compose -f docker-compose.test.yml exec -T backend pytest --junitxml=pytest-report.xml

      - name: Run tests with pytest
        run: pytest --junitxml=pytest-report-${{ matrix.python-version }}.xml

      # Optionnel: Sauvegarder le rapport de test
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports-${{ matrix.python-version }}
          path: pytest-report-${{ matrix.python-version }}.xml
        # 'if: always()' garantit que cette étape s'exécute même si les tests échouent,
        # pour que vous puissiez toujours récupérer le rapport.
        if: always()


      - name: Stop services
        if: always()
        run: docker-compose -f docker-compose.test.yml down

